version: '3.1'

services:
  register-qemu:
    privileged: true
    image: multiarch/qemu-user-static:register
  node:
    build:
      image: valentinvieriu/alpine-node-arm:8.1.2
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=8.1.2