version: '3.3'

services:
  register-qemu:
    privileged: true
    image: multiarch/qemu-user-static:register
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}