version: '3.3'

services:
  node:
    image: valentinvieriu/alpine-node-arm:${NODE_VERSION}
    # image: valentinvieriu/alpine-node-arm:latest
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}