version: '3.1'

services:
  node:
    image: valentinvieriu/alpine-node-arm:8.1.2
    # image: valentinvieriu/alpine-node-arm:latest
    build:
      context: .
      args:
        - NODE_VERSION=8.1.2